#ifndef FILESHIELD_PERSIST_H
#define FILESHIELD_PERSIST_H

#include <sys/types.h>
#include <stddef.h>
#include <limits.h>
#include <stdio.h>

#define PERSIST_MAX_ENTRIES 256
#define PERSIST_CHAIN_MAX 3
#define PERSIST_CMDLINE_MAX 512 /* matches the /proc/<pid>/cmdline read buffer */
#define PERSIST_STATE_DIR "/var/lib/fileshield"
#define PERSIST_STATE_FILE PERSIST_STATE_DIR "/runtime-allowlist.json"
#define PERSIST_DENY_STATE_FILE PERSIST_STATE_DIR "/runtime-denylist.json"

/*
 * Serialized-size bounds shared by every JSON state file (the runtime
 * lists and the pin table).  A PATH_MAX-1 field can expand sixfold via
 * \uXXXX escapes, so the writer's escape scratch needs 6*PATH_MAX + a
 * wrapper margin, and the parser's line buffer the same plus the key
 * wrapper.  One convention instead of two: a line any state writer
 * emits always fits every state reader.
 */
#define JSON_ESCAPED_MAX (PATH_MAX * 6 + 8)
#define JSON_LINE_MAX (PATH_MAX * 6 + 256)

/*
 * Persistent runtime allowlist entry: mirrors a DynAllowEntry from fanotify.c
 * but is meant to be serialized to JSON and reloaded on daemon restart.
 */
typedef struct
{
    /* Stable rule identifier: 16 lowercase hex chars + NUL, generated by
     * the daemon at creation.  A legacy entry (no stored key) keeps an
     * empty ID until the daemon migrates it. */
    char rule_id[17];
    char binary[PATH_MAX];
    char binary_sha512[129];
    char target_path[PATH_MAX];
    char cmdline[PERSIST_CMDLINE_MAX]; /* raw command line (audit/display)  */
    char cmdline_sha512[129];          /* matching key for the command line */
    char chain_comm[PERSIST_CHAIN_MAX][256];
    char chain_sha512[PERSIST_CHAIN_MAX][129];
    int chain_depth;
    time_t created_at;
} PersistEntry;

/*
 * Public API: load and save persistent entries
 */

/* Load persisted entries from JSON file. Returns count of entries loaded, or -1 on error. */
int persist_load(const char *filepath, PersistEntry *out_entries, int max_entries);

/* Save entries to JSON file. Returns 0 on success, -1 on error. */
int persist_save(const char *filepath, const PersistEntry *entries, int count);

/*
 * Shared JSON and atomic-write primitives.  pin.c reuses these so every
 * state file is escaped and committed exactly like the runtime lists.
 */

/*
 * Escape src for embedding inside a double-quoted JSON string (quotes,
 * backslashes and control characters).  Writes at most dst_size-1 bytes
 * plus the terminating NUL and returns the number of bytes written, or
 * -1 when the value does not fit or an argument is NULL.
 */
int persist_json_escape(const char *src, char *dst, size_t dst_size);

/*
 * Extract the first "key": "value" string pair from one JSON line,
 * decoding escape sequences.  Returns 1 and fills key_out/out when a
 * string pair was found, 0 for numeric values, malformed input, or when
 * the decoded value does not fit.  out is always NUL-terminated on
 * success (on failure it holds an empty string).
 */
int persist_json_extract_string(const char *line, char *key_out, size_t keysz,
                                char *out, size_t outsz);

/*
 * Root-run trust bar shared by the state loaders.  When geteuid()==0,
 * refuse a path that is itself a symlink (lstat), or a regular file that
 * is not root-owned or is group/other-writable (fstat of the already
 * opened fp) -- the same bar as config_load().  Non-regular sources are
 * left to the parser, and non-root runs always pass (tests and the CLI
 * fallback stay unaffected).  Returns 0 when trusted, -1 when refused,
 * logging why under the caller tag 'what' (e.g. "persist_load").
 * Callers handle ENOENT before opening: this runs only after a
 * successful fopen.
 */
int persist_file_trusted(FILE *fp, const char *filepath, const char *what);

/*
 * Atomically write text (a NUL-terminated string, written without its
 * NUL) to filepath: the parent directory is created when missing (0700,
 * root-ownership and symlink checks), the bytes go to a 0600 temp file
 * opened O_EXCL|O_CLOEXEC|O_NOFOLLOW, and the temp file is renamed over
 * filepath.  Returns 0 on success; -1 on any failure.  A failure before
 * the rename removes the temp file and leaves any existing filepath
 * untouched; a directory-fsync failure after the rename is reported as
 * -1 even though the new file is already in place (it may not survive a
 * crash).
 */
int persist_write_text(const char *filepath, const char *text);

/*
 * Test seam: make the (nth+1)-th fsync call fail with EIO (nth = 0 fails
 * the first call, 1 the second, ...).  Any negative value disables the
 * injection.  Used by test_persist to exercise the fsync failure
 * branches on any filesystem.
 */
void persist_test_fail_fsync_after(int nth);

#endif
